kind: pipeline
name: default

steps:
- name: test
  image: python:3.7-alpine
  commands:
  - apk add --no-cache --update python3-dev  gcc build-base
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pytest

trigger:
  event: push
