"""
Copyright (c) 2025 SignalWire

This file is part of the SignalWire SDK.

Licensed under the MIT License.
See LICENSE file in the project root for full license information.
"""

"""
Deprecated SWML verbs are not SDK surface, statically or at runtime.

The SWML schema marks ``dial``, ``eval`` and ``if`` ``"deprecated": true``, and
they are not exposed (owner ruling 2026-09-24). Two surfaces must agree:

* the static stub ``swml_verbs_generated._SwmlVerbs`` (what a type checker sees),
  generated by porting-sdk's generate_python_rest_types.py, which drops a verb
  the schema flags; and
* the runtime methods ``SWMLBuilder`` / ``SWMLService`` install from the schema
  (``SchemaUtils.get_all_verb_names``), which skip a flagged verb the same way.

The runtime tests drive the real installer over the bundled schema plus
synthetic deprecated wrappers, so they hold whichever schema ships.
"""

import copy
from typing import Any

import pytest

from signalwire.core import swml_verbs_generated as gen
from signalwire.core.swml_builder import SWMLBuilder
from signalwire.core.swml_service import SWMLService

_DEPRECATED = {"Dial": "dial", "Eval": "eval", "If": "if"}


def _service_with_verbs(deprecated_flag: bool) -> SWMLService:
    """A service whose schema carries dial/eval/if, flagged or not."""
    service = SWMLService(name="deprecated-verbs", route="/deprecated")
    utils = service.schema_utils
    assert utils is not None
    schema: dict[str, Any] = copy.deepcopy(utils.schema)
    defs = schema["$defs"]
    for wrapper, verb in _DEPRECATED.items():
        inner: dict[str, Any] = {
            "type": "object",
            "properties": {"to": {"type": "string"}},
        }
        if deprecated_flag:
            inner["deprecated"] = True
        defs[wrapper] = {
            "type": "object",
            "properties": {verb: inner},
            "required": [verb],
        }
        defs["SWMLMethod"]["anyOf"].append({"$ref": f"#/$defs/{wrapper}"})
    utils.schema = schema
    utils.verbs = utils._extract_verb_definitions()
    utils._init_full_validator()
    return service


def _ann(cls: type, field: str) -> str:
    """A TypedDict field's annotation text (a string, or a ForwardRef wrapping one,
    depending on the Python version, under ``from __future__ import annotations``)."""
    ann = cls.__annotations__[field]
    return str(getattr(ann, "__forward_arg__", ann))


class TestStaticStub:
    """The generated _SwmlVerbs stub."""

    @pytest.mark.parametrize("method", ["dial", "eval", "if_"])
    def test_deprecated_verb_has_no_stub_method(self, method: str) -> None:
        assert not hasattr(gen._SwmlVerbs, method)

    @pytest.mark.parametrize("cls", ["Dial", "Eval", "If"])
    def test_deprecated_verb_has_no_wrapper_type(self, cls: str) -> None:
        assert not hasattr(gen, cls)

    def test_non_deprecated_verb_has_stub_method(self) -> None:
        assert callable(gen._SwmlVerbs.connect)
        assert callable(gen._SwmlVerbs.transfer)

    def test_ai_verb_body_keeps_its_typed_config(self) -> None:
        """AI.ai is the typed AiConfig TypedDict (plus its positional and scalar
        forms), not a flattened dict[str, Any]."""
        assert _ann(gen.AI, "ai").startswith("AiConfig | ")
        assert _ann(gen.AiConfig, "params") == "AiParams"
        assert _ann(gen.AiConfig, "prompt") == "AiPrompt"
        assert "ai_model" in gen.AiParams.__annotations__


class TestRuntimeInstaller:
    """The methods SWMLBuilder / SWMLService install from the schema at runtime."""

    def test_deprecated_verbs_are_not_installed(self) -> None:
        service = _service_with_verbs(deprecated_flag=True)
        builder = SWMLBuilder(service)
        names = service.schema_utils.get_all_verb_names()
        for verb in _DEPRECATED.values():
            assert verb not in names
            assert not hasattr(builder, verb)
            assert not hasattr(service, verb)

    def test_non_deprecated_verbs_are_installed(self) -> None:
        service = _service_with_verbs(deprecated_flag=True)
        builder = SWMLBuilder(service)
        assert callable(builder.connect)
        assert callable(builder.transfer)

    def test_dropping_the_flag_installs_the_verb(self) -> None:
        """Negative control: the schema flag alone hides the verb. The same wrappers
        without it are installed, so the skip is keyed on the flag, not the name."""
        service = _service_with_verbs(deprecated_flag=False)
        builder = SWMLBuilder(service)
        names = service.schema_utils.get_all_verb_names()
        for verb in _DEPRECATED.values():
            assert verb in names
        builder.dial(to="+15551230000")
        assert {"dial": {"to": "+15551230000"}} in service.get_document()["sections"][
            "main"
        ]

    def test_deprecated_verb_is_still_known_to_validation(self) -> None:
        """Skipping the method does not make an existing document carrying the
        verb unknown: the verb stays in the schema's verb table."""
        service = _service_with_verbs(deprecated_flag=True)
        assert "dial" in service.schema_utils.verbs
