"""SignalWire RELAY client — real-time call control over WebSocket."""

from .client import RelayClient, RelayError
from .call import (
    Call,
    Action,
    PlayAction,
    RecordAction,
    DetectAction,
    CollectAction,
    StandaloneCollectAction,
    FaxAction,
    TapAction,
    StreamAction,
    PayAction,
    TranscribeAction,
    AIAction,
)
from .message import Message
from .event import (
    RelayEvent,
    CallStateEvent,
    CallReceiveEvent,
    PlayEvent,
    RecordEvent,
    CollectEvent,
    ConnectEvent,
    DetectEvent,
    FaxEvent,
    TapEvent,
    StreamEvent,
    SendDigitsEvent,
    DialEvent,
    ReferEvent,
    DenoiseEvent,
    PayEvent,
    QueueEvent,
    EchoEvent,
    TranscribeEvent,
    HoldEvent,
    ConferenceEvent,
    CallingErrorEvent,
    MessageReceiveEvent,
    MessageStateEvent,
    parse_event,
)
from .constants import (
    CALL_STATE_CREATED,
    CALL_STATE_RINGING,
    CALL_STATE_ANSWERED,
    CALL_STATE_ENDING,
    CALL_STATE_ENDED,
    CONNECT_STATE_CONNECTING,
    CONNECT_STATE_CONNECTED,
    CONNECT_STATE_DISCONNECTED,
    CONNECT_STATE_FAILED,
    EVENT_CALL_STATE,
    EVENT_CALL_RECEIVE,
    EVENT_CALL_PLAY,
    EVENT_CALL_RECORD,
    EVENT_CALL_COLLECT,
    EVENT_CALL_CONNECT,
    EVENT_CALL_DETECT,
    EVENT_CALL_FAX,
    EVENT_CALL_TAP,
    EVENT_CALL_STREAM,
    EVENT_CALL_SEND_DIGITS,
    EVENT_CALL_DIAL,
    EVENT_CALL_REFER,
    EVENT_CALL_DENOISE,
    EVENT_CALL_PAY,
    EVENT_CALL_QUEUE,
    EVENT_CALL_ECHO,
    EVENT_CALL_TRANSCRIBE,
    EVENT_CONFERENCE,
    EVENT_CALLING_ERROR,
    EVENT_MESSAGING_RECEIVE,
    EVENT_MESSAGING_STATE,
    MESSAGE_STATE_QUEUED,
    MESSAGE_STATE_INITIATED,
    MESSAGE_STATE_SENT,
    MESSAGE_STATE_DELIVERED,
    MESSAGE_STATE_UNDELIVERED,
    MESSAGE_STATE_FAILED,
    MESSAGE_STATE_RECEIVED,
)

__all__ = [
    # Client
    "RelayClient",
    "RelayError",
    # Call + Actions
    "Call",
    "Action",
    "PlayAction",
    "RecordAction",
    "DetectAction",
    "CollectAction",
    "StandaloneCollectAction",
    "FaxAction",
    "TapAction",
    "StreamAction",
    "PayAction",
    "TranscribeAction",
    "AIAction",
    # Message
    "Message",
    # Events
    "RelayEvent",
    "CallStateEvent",
    "CallReceiveEvent",
    "PlayEvent",
    "RecordEvent",
    "CollectEvent",
    "ConnectEvent",
    "DetectEvent",
    "FaxEvent",
    "TapEvent",
    "StreamEvent",
    "SendDigitsEvent",
    "DialEvent",
    "ReferEvent",
    "DenoiseEvent",
    "PayEvent",
    "QueueEvent",
    "EchoEvent",
    "TranscribeEvent",
    "HoldEvent",
    "ConferenceEvent",
    "CallingErrorEvent",
    "MessageReceiveEvent",
    "MessageStateEvent",
    "parse_event",
    # Constants — call states
    "CALL_STATE_CREATED",
    "CALL_STATE_RINGING",
    "CALL_STATE_ANSWERED",
    "CALL_STATE_ENDING",
    "CALL_STATE_ENDED",
    # Constants — connect states
    "CONNECT_STATE_CONNECTING",
    "CONNECT_STATE_CONNECTED",
    "CONNECT_STATE_DISCONNECTED",
    "CONNECT_STATE_FAILED",
    # Constants — event types
    "EVENT_CALL_STATE",
    "EVENT_CALL_RECEIVE",
    "EVENT_CALL_PLAY",
    "EVENT_CALL_RECORD",
    "EVENT_CALL_COLLECT",
    "EVENT_CALL_CONNECT",
    "EVENT_CALL_DETECT",
    "EVENT_CALL_FAX",
    "EVENT_CALL_TAP",
    "EVENT_CALL_STREAM",
    "EVENT_CALL_SEND_DIGITS",
    "EVENT_CALL_DIAL",
    "EVENT_CALL_REFER",
    "EVENT_CALL_DENOISE",
    "EVENT_CALL_PAY",
    "EVENT_CALL_QUEUE",
    "EVENT_CALL_ECHO",
    "EVENT_CALL_TRANSCRIBE",
    "EVENT_CONFERENCE",
    "EVENT_CALLING_ERROR",
    # Constants — messaging event types
    "EVENT_MESSAGING_RECEIVE",
    "EVENT_MESSAGING_STATE",
    # Constants — message states
    "MESSAGE_STATE_QUEUED",
    "MESSAGE_STATE_INITIATED",
    "MESSAGE_STATE_SENT",
    "MESSAGE_STATE_DELIVERED",
    "MESSAGE_STATE_UNDELIVERED",
    "MESSAGE_STATE_FAILED",
    "MESSAGE_STATE_RECEIVED",
]
