"""SignalWire RELAY client — real-time call control over WebSocket."""

from .client import RelayClient, RelayError
from .call import Call, PlayAction, RecordAction, DetectAction, CollectAction, Action
from .event import (
    RelayEvent,
    CallStateEvent,
    CallReceiveEvent,
    PlayEvent,
    RecordEvent,
    CollectEvent,
    ConnectEvent,
    DetectEvent,
    parse_event,
)
from .constants import (
    CALL_STATE_CREATED,
    CALL_STATE_RINGING,
    CALL_STATE_ANSWERED,
    CALL_STATE_ENDING,
    CALL_STATE_ENDED,
    CONNECT_STATE_CONNECTING,
    CONNECT_STATE_CONNECTED,
    CONNECT_STATE_DISCONNECTED,
    CONNECT_STATE_FAILED,
    EVENT_CALL_STATE,
    EVENT_CALL_RECEIVE,
    EVENT_CALL_PLAY,
    EVENT_CALL_RECORD,
    EVENT_CALL_COLLECT,
    EVENT_CALL_CONNECT,
    EVENT_CALL_DETECT,
)

__all__ = [
    "RelayClient",
    "RelayError",
    "Call",
    "Action",
    "PlayAction",
    "RecordAction",
    "DetectAction",
    "CollectAction",
    "RelayEvent",
    "CallStateEvent",
    "CallReceiveEvent",
    "PlayEvent",
    "RecordEvent",
    "CollectEvent",
    "ConnectEvent",
    "DetectEvent",
    "parse_event",
    "CALL_STATE_CREATED",
    "CALL_STATE_RINGING",
    "CALL_STATE_ANSWERED",
    "CALL_STATE_ENDING",
    "CALL_STATE_ENDED",
    "CONNECT_STATE_CONNECTING",
    "CONNECT_STATE_CONNECTED",
    "CONNECT_STATE_DISCONNECTED",
    "CONNECT_STATE_FAILED",
    "EVENT_CALL_STATE",
    "EVENT_CALL_RECEIVE",
    "EVENT_CALL_PLAY",
    "EVENT_CALL_RECORD",
    "EVENT_CALL_COLLECT",
    "EVENT_CALL_CONNECT",
    "EVENT_CALL_DETECT",
]
